# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:			[jekyll-paginate, jekyll-gist]
# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ajay Kavuri
tagline:          'Computer Science Jedi'
description:      'Pseudo Codes for Pseudo World'
url:              http://pseudoaj.com
baseurl:          /

author:           
  name:           'Ajay Krishna Teja Kavuri'
  url:            https://twitter.com/pseudoaj

paginate:         5

github:           
  repo:           https://github.com/pseudoaj/hyde/
