# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:			[jekyll-paginate, jekyll-gist]
# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ajay Krishna Teja Kavuri
tagline:          'Pseudo Codes for Pseudo World'
description:      'Computer Science Jedi'
url:              http://pseudoaj.com
baseurl:          /

author:
  name:           'Ajay Krishna Teja Kavuri'
  url:            https://twitter.com/pseudoaj

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pseudoaj/hyde/
